# Generated by Django 4.0 on 2021-12-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0009_alter_channel_music_alter_channel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='music',
        ),
    ]
