# Generated by Django 4.0 on 2021-12-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0011_channel_music'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
