# Generated by Django 4.0 on 2021-12-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0013_alter_history_music_id_alter_watchlater_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='music_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='video_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
