# Generated by Django 4.0 on 2021-12-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0014_alter_history_music_id_alter_watchlater_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='movie',
            field=models.CharField(default='', max_length=100000000),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='video_id',
            field=models.CharField(blank=True, default='', max_length=100000000, null=True),
        ),
    ]
