# Generated by Django 4.0 on 2021-12-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0015_alter_song_movie_alter_watchlater_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='music_id',
            field=models.CharField(blank=True, default='', max_length=1000000000, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='movie',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='video_id',
            field=models.CharField(blank=True, default='', max_length=1000000000, null=True),
        ),
    ]
