# Generated by Django 4.0 on 2021-12-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0018_history2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History2',
        ),
    ]
