# Generated by Django 4.0 on 2021-12-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0020_alter_history_music_id_alter_watchlater_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='music_id',
            field=models.CharField(default=True, max_length=500000000),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='video_id',
            field=models.CharField(default=True, max_length=500000000),
        ),
    ]
